"""Comparison engines: folder tree compare and text diff."""

from .folder import (
    CompareCancelled,
    CompareDone,
    CompareEvent,
    CompareOptions,
    ContentChecked,
    ContentMode,
    DirScanned,
    NodeResult,
    Status,
    compare_folders,
)
from .text import (
    BlockKind,
    DecodedText,
    DiffBlock,
    Row,
    TextDiffOptions,
    align_rows,
    apply_copy_section,
    block_index_for_left_line,
    compute_rows,
    condense_rows,
    decode_bytes,
    diff_lines,
    diff_run_starts,
    encode_text,
)

__all__ = [
    "BlockKind",
    "CompareCancelled",
    "CompareDone",
    "CompareEvent",
    "CompareOptions",
    "ContentChecked",
    "ContentMode",
    "DecodedText",
    "DiffBlock",
    "DirScanned",
    "NodeResult",
    "Row",
    "Status",
    "TextDiffOptions",
    "align_rows",
    "apply_copy_section",
    "block_index_for_left_line",
    "compare_folders",
    "compute_rows",
    "encode_text",
    "condense_rows",
    "decode_bytes",
    "diff_lines",
    "diff_run_starts",
]
